# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

variables:
    IMAGE_NAME: faco400/gces_pipeline
    IMAGE_TAG: gces-app-1.0
    POSTGRES_DB: library_db
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_HOST: db
    POSTGRES_PORT: 5432

stages:          # List of stages for jobs, and their order of execution
  - build
  - lint
  - test
  # - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: tmaier/docker-compose:latest
  services:
    - docker:20.10.16-dind
  before_script:
    - docker info
    - docker-compose --version
    - docker login -u ${REGISTRY_USER//0}00 -p $REGISTRY_PASS
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose push
  
test-job:
  stage: test
  image: docker:latest

  services:
  - docker:dind

  before_script:
  - apk add --update python py-pip python-dev && pip install docker-compose # install docker-compose
  - docker version
  - docker-compose version

  script:
  - docker-compose up -d db
  - docker-compose up -d web
  - docker exec -it web_container /bin/bash
  - python3 manage.py test


# unit-test-job:   # This job runs in the test stage.
#   stage: test    # It only starts when the job in the build stage completes successfully.
#   image: python:3.9.5-slim-buster
#   services:
#     - tmaier/docker-compose:latest
#     - docker:20.10.16-dind
#   before_script:
#     - apt-get update
#     - apt-get -y install libpq-dev gcc
#     - pip3 install -r ./library_back/requirements.txt
#   script:
#     - docker-compose up db
#     - docker-compose up web
#     - cd ./library_back/
#     - python3 manage.py makemigrations
#     - python3 manage.py migrate
#     # - python3 manage.py runserver 0.0.0.0:8000
#     - python3 manage.py test

lint-job:   # This job also runs in the test stage.
  stage: lint    # It can run at the same time as unit-test-job (in parallel).
  image: nikolaik/python-nodejs:python3.9-nodejs18-slim
  before_script:
    - pip install pylint
    - npm install eslint
    - apt-get update
    - apt-get -y install libpq-dev gcc
    - pip install -r ./library_back/requirements.txt
  script:
    - pylint library_back/
    - npx eslint library_front/

# deploy-job:      # This job runs in the deploy stage.
#   stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   environment: production
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
