version: "3.9"
   
services:
  db:
    image:  postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    container_name: db_container

  web:
    build:
      context: ./library_back
    command: bash  -c "
        python manage.py makemigrations
        && python manage.py migrate
        && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./library_back:/app
    environment:
      - POSTGRES_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: web_container
  
  front:
    build:
      context: ./library_front
    command: npm start
    volumes:
      - front_build:/library_front/build
    ports:
      - "3000:3000"
    depends_on:
      - web
    container_name: front_container
  
  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - front_build:/var/www/library_front
    depends_on:
    - web
    - front
volumes:
  front_build:

    


