version: "3.9"
   
services:
  db:
    image:  postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
  
  web:
    build:
      context: library_back
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./library_back:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
